I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 30, in script
    $ ordemEscolha = selectordemEscolha()
  File "game/script.rpy", line 30, in <module>
    $ ordemEscolha = selectordemEscolha()
  File "game/bd.rpy", line 111, in selectordemEscolha
    ordemEscolha = resultado[2]
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 30, in script
    $ ordemEscolha = selectordemEscolha()
  File "C:\Users\Etec Paulino Botelho\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Etec Paulino Botelho\Downloads\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 30, in <module>
    $ ordemEscolha = selectordemEscolha()
  File "game/bd.rpy", line 111, in selectordemEscolha
    ordemEscolha = resultado[2]
IndexError: list index out of range

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.2.24090902
Trilhas do Brasil 1.0
Tue Sep 17 21:00:30 2024
